[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "muse2-to-live"
version = "0.1.0"
description = "Muse 2 LSL to OSC bridge"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "muselsl",
  "pylsl==1.18.2",
  "python-osc",
  "matplotlib",
  "numpy",
]

[project.scripts]
muse2-osc = "muse2_to_live.stream_to_osc:main"
muse2-viewer = "muse2_to_live.brainwaves_viewer:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
